name: Flutter CI - Unit Tests
run-name: Deployed by @${{ github.actor }}
on:
  pull_request:
    branches: [ "main", "develop" ]
    types: [labeled, opened, synchronize, reopened]

jobs:
    flutter_unit_test:
      
        name: Run Flutter test and analyze DevTools
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
          - name: Checkout the branch
            uses: actions/checkout@v3

          - name: Setup Flutter SDK
            uses: subosito/flutter-action@v2
            with:
              channel: 'stable'
              flutter-version: 3.10.5
              cache: true

          - name: Get Packages
            run: flutter pub get
          - name: Detect errors or inefficiencies
            run: flutter analyze --fatal--warnings
          - name: Run Unit Tests
            run: flutter test
        
